[default]
template_dir = "templates/"

[default.databases.sea_orm]
# Postgres
# make sure to enable "sqlx-postgres" feature in Cargo.toml, i.e default = ["sqlx-postgres"]
url = "postgres://root:root@localhost/rocket_example"