edition = "2021"
max_width = 100
hard_tabs = false
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Max"
wrap_comments = true
normalize_doc_attributes = true
comment_width = 100
format_code_in_doc_comments = true