[application]
name = "Counted"
default_platform = "android"

[bundle]
identifier = "fr.counted.app"
publisher = "Counted"
icon = ["assets/favicon.ico"]

[bundle.android]
min_sdk_version = 24
target_sdk_version = 33
